### ISSUE TITLE
Broken Image Links

### ISSUE THREAD

**Issue by capjan** [Sarenor/arsnouveau-wiki#14]
I've found some broken image links.

**Comment by capjan** [comment]
![image](https://user-images.githubusercontent.com/3989034/223052023-bfd4d57c-2e89-4b39-bb74-af47c8b28d27.png)

**Comment by capjan** [comment]
![image](https://user-images.githubusercontent.com/3989034/223052301-929bc9b2-1a7f-4678-a223-acf81a1d5c71.png)

**Comment by capjan** [comment]
Just as examples. Maybe adding an automated broken link checking?

**Comment by Sarenor** [comment]
Actually that shouldn't be too difficult, why didn't I think about that before? 🤔

**Comment by Sarenor** [comment]
![image](https://user-images.githubusercontent.com/31982384/223489038-8199fe2b-190e-4026-8d2d-dc18b3d96112.png)
Also got a bit of an issue with the enchanters eye and can't catch that with a generic "does this image exist"

**Comment by Sarenor** [comment]
temporarily resolved until I have the time to add broken image link tracking: https://github.com/Sarenor/arsnouveau-wiki/issues/19
