### ISSUE TITLE
Stripped Flashing Archwood Log

### ISSUE THREAD

**Issue by SalaciousShadow** [Sarenor/arsnouveau-wiki#21]
Stripped Flashing Archwood Log is suspected of missing the Stripped_Log tag due to incompatibility with Create's Stripped Log + Andesite Alloy = Andesite Casing mechanic. This mechanic functions for other Stripped Archwood Logs besides Stripped Flashing Archwood Log. (assumed to be related to Flashing Archwood being listed separately from the other Archwoods in the spellbook documentation) 

[Discovered while using a Valhelsia 6 modpack [v6.1.0] but was instructed by the Valhelsia team to bring this to the attention of the Ars Nouveau Team so that it can be fixed at the source to benefit all Ars-using packs rather than patched solely on Valhelsia's end]

**Comment by Sarenor** [comment]
This is the wiki, not the mod that includes flashing archwood. That'd be https://github.com/Alexthw46/Ars-Elemental but I'll pass it on!
Thanks and sorry for the delay, life happened and I missed the notification.
